CREATE TABLE groups (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL
);

INSERT INTO groups (id, name) VALUES (0, 'root');

ALTER TABLE hosts ADD COLUMN group_id INTEGER NOT NULL DEFAULT 0 REFERENCES groups (id) ON DELETE RESTRICT;
ALTER TABLE hosts ALTER group_id DROP DEFAULT;